[phases.setup]
  nixPkgs = ["nodejs-18_x"]

[phases.install]
  cmds = ["npm install", "cd client && npm install --legacy-peer-deps"]

[phases.build]
  cmds = ["cd client && npm run build"]

[start]
  cmd = "npm start"
